# Generated by Django 4.0.1 on 2022-05-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('society', models.CharField(choices=[('lahore', 'DHA LAHORE'), ('gujranwala', 'DHA GUJRANWALA'), ('multan', 'DHA MULTAN'), ('peshawar', 'DHA PESHAWAR'), ('lakecityl', 'LAKE CITY LAHORE'), ('nfcl', 'NFC LAHORE'), ('statelifel', 'STATE LIFE LAHORE'), ('ldacityl', 'LDA CITY LAHORE'), ('etihadtownl', 'ETIHAD TOWN LAHORE'), ('capitalsmartcityi', 'CAPITAL SMART CITY ISLAMABAD'), ('lahoresmartcity', 'LAHORE SMART CITY'), ('palmcityl', 'PALM CITY LAHORE'), ('midcityl', 'MID CITY LAHORE'), ('kingtownl', 'KING TOWN LAHORE'), ('wapdatownl', 'WAPDA TOWN LAHORE'), ('valenciatown', 'VALENCIA TOWN'), ('khayabaneamin', 'KHAYABAN E AMIN'), ('gulberg', 'GULBERG'), ('suigasphases', 'SUI GAS PHASES'), ('hbfcl', 'HBFC LAHORE'), ('chinarbaghl', 'CHINAR BAGH LAHORE'), ('awtl', 'AWT LAHORE'), ('alkabirtown', 'AL KABIR TOWN'), ('bahriatown', 'BAHRIA TOWN')], default='lahore', max_length=30)),
                ('phase', models.IntegerField(default=0)),
                ('property_Type', models.CharField(choices=[('plot', 'Plot'), ('house', 'House'), ('file', 'File'), ('commercial', 'Commercial')], default='plot', max_length=30)),
                ('file_Type', models.CharField(choices=[('na', 'N/A'), ('Residential Plot', 'Residential Plot'), ('Commercial Plot', 'Commercial Plot')], default='na', max_length=40)),
                ('area', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('contact_Name', models.CharField(max_length=100)),
                ('contact_Num', models.CharField(max_length=100)),
                ('Note', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=150)),
                ('video_title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
